const stockLogoUrl=symbol=>`https://financialmodelingprep.com/image-stock/${encodeURIComponent(symbol)}.png`;
const stockLogoMarkup=(symbol,fallback=symbol.slice(0,2),className='mini-logo')=>`<span class="${className} remote-stock-logo"><img src="${stockLogoUrl(symbol)}" alt="${symbol} 公司 Logo" loading="lazy" referrerpolicy="no-referrer" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="logo-fallback" hidden>${fallback}</span></span>`;

const stocks=[
 {symbol:'NVDA',name:'NVIDIA',sector:'半导体',cat:'ai',logo:'NV',logoBg:'#111',price:187.42,day:4.28,session:0.62,week:6.84,month:18.40,ytd:64.10,rvol:2.7,avgVol:'54.2M',marketCap:'4.61T',high:-3.8,pe:38.5,sectorPe:26.3,fwdPe:31.2,ps:21.3,revGrowth:'+34.2%',epsGrowth:'+41.8%',btc:0.42,eth:0.36,nasdaq:0.89,beta:'1.71',event:'12天后财报',earningsMove:'+7.4%',btcSensitivity:'0.38×',summary:'AI 芯片板块整体走强，成交量达到 20 日均值的 2.7 倍，股价距离 52 周高点仅 3.8%，正在测试前高压力区。',valuationNote:'当前 PE 高于半导体行业平均，但仍低于部分历史极端高估区。若盈利继续超预期，估值仍有被消化的空间。',cryptoNote:'对于 NVDA 这类科技龙头，BTC 相关性更适合用来观察跨市场风险偏好，而不是直接作为核心定价锚。',events:[{title:'下次财报 · 12天后',desc:'市场将重点关注收入增速、毛利率、AI 芯片需求及下一季度指引。'}, {title:'上次财报后 +7.4%',desc:'说明财报窗口依旧容易形成方向性波动，但也可能伴随高波动回撤。'}, {title:'未来 7 天宏观风险',desc:'关注就业数据与美债收益率变化，它们会直接影响成长股估值框架。'}]},
 {symbol:'COIN',name:'Coinbase',sector:'加密概念',cat:'crypto',logo:'CO',logoBg:'#6f4dff',price:391.18,day:6.12,session:1.04,week:8.55,month:26.38,ytd:58.60,rvol:3.4,avgVol:'16.8M',marketCap:'98.1B',high:-7.6,pe:31.8,sectorPe:22.4,fwdPe:28.9,ps:12.6,revGrowth:'+24.7%',epsGrowth:'+29.5%',btc:0.76,eth:0.63,nasdaq:0.62,beta:'1.88',event:'21天后财报',earningsMove:'+9.6%',btcSensitivity:'1.21×',summary:'COIN 与 BTC 维持较高正相关，同时成交量显著放大。适合结合 BTC 趋势、加密成交活跃度与公司事件共同判断。',valuationNote:'估值高于传统券商，但市场给予其加密生态入口溢价。关键在于交易量与稳定币收入能否延续。',cryptoNote:'BTC 与 ETH 的趋势、现货 ETF 资金流与整体加密成交热度，都可能直接影响 COIN 的短线方向。',events:[{title:'下次财报 · 21天后',desc:'重点观察现货/衍生品交易量、稳定币业务与国际扩张进展。'}, {title:'BTC 风险偏好回升',desc:'若加密市场继续活跃，COIN 往往会同时受益于交易量和情绪改善。'}, {title:'监管动态',desc:'任何关于加密监管的正负面消息，都会显著放大股价波动。'}]},
 {symbol:'MSTR',name:'Strategy',sector:'加密概念',cat:'crypto',logo:'MS',logoBg:'#f05b3d',price:463.71,day:5.84,session:-0.20,week:9.18,month:31.05,ytd:72.40,rvol:3.0,avgVol:'14.2M',marketCap:'128.3B',high:-9.4,pe:null,sectorPe:null,fwdPe:null,ps:'—',revGrowth:'+11.2%',epsGrowth:'—',btc:0.82,eth:0.66,nasdaq:0.58,beta:'2.11',event:'18天后业绩',earningsMove:'+6.8%',btcSensitivity:'1.65×',summary:'MSTR 对 BTC 价格具有明显放大弹性。短线观察重点不是传统估值，而是 BTC 趋势、公司持币策略及股价相对净资产溢价。',valuationNote:'对 MSTR 来说，传统 PE 参考意义较弱，更适合观察企业持币规模、融资能力及股价对净资产的溢价水平。',cryptoNote:'MSTR 是最直接的 BTC beta 代理之一，对比 COIN 更偏资产价格驱动，而非交易量驱动。',events:[{title:'下次业绩更新 · 18天后',desc:'重点看持币变化、融资动作与软件业务表现。'}, {title:'BTC 价格高相关',desc:'若 BTC 延续趋势，MSTR 往往会出现更高弹性。'}, {title:'溢价观察',desc:'需关注股价相对持币净值的溢价是否持续扩大。'}]},
 {symbol:'TSLA',name:'Tesla',sector:'EV',cat:'earnings',logo:'TS',logoBg:'#d92b2b',price:342.06,day:-2.18,session:0.42,week:-1.44,month:8.70,ytd:19.80,rvol:1.9,avgVol:'89.6M',marketCap:'1.09T',high:-18.5,pe:92.4,sectorPe:28.1,fwdPe:71.3,ps:9.1,revGrowth:'+8.6%',epsGrowth:'-5.1%',btc:0.36,eth:0.28,nasdaq:0.74,beta:'1.96',event:'2天后财报',earningsMove:'+11.8%',btcSensitivity:'0.27×',summary:'财报临近使预期波动升高。当前股价跑输大盘，但盘后情绪有所修复，交易重点转向财报指引与毛利率。',valuationNote:'PE 仍明显高于汽车行业平均，市场更多在交易长期叙事。若指引不及预期，高估值更容易放大回撤。',cryptoNote:'TSLA 与加密相关性有限，更适合与纳指风险偏好、利率环境和公司事件一起观察。',events:[{title:'季度财报 · 2天后',desc:'关注汽车毛利率、Robotaxi 节奏与全年交付指引。'}, {title:'上次财报后 +11.8%',desc:'历史上财报后通常伴随方向性大波动。'}, {title:'利率敏感',desc:'美债收益率回升时，高估值成长股往往承压。'}]},
 {symbol:'AVGO',name:'Broadcom',sector:'半导体',cat:'ai',logo:'AV',logoBg:'#2869e9',price:281.64,day:2.44,session:0.19,week:4.06,month:12.20,ytd:38.20,rvol:1.5,avgVol:'29.4M',marketCap:'1.31T',high:-5.1,pe:34.2,sectorPe:26.3,fwdPe:29.8,ps:18.7,revGrowth:'+22.1%',epsGrowth:'+19.4%',btc:0.39,eth:0.30,nasdaq:0.84,beta:'1.33',event:'16天后财报',earningsMove:'+5.1%',btcSensitivity:'0.34×',summary:'AI 相关需求继续为板块提供支撑，当前表现强于行业平均，但成交量尚未达到异常爆量级别。',valuationNote:'估值高于行业平均但低于部分高弹性 AI 标的，属于相对稳健的半导体龙头。',cryptoNote:'更适合作为科技板块强弱观察标的，与 BTC 的直接联动相对有限。',events:[{title:'下次财报 · 16天后',desc:'重点关注 AI 相关收入占比与企业基础设施需求。'}, {title:'上次财报后 +5.1%',desc:'通常体现为稳健而非极端爆发的财报反应。'}, {title:'AI 板块共振',desc:'若板块继续扩散，AVGO 往往提供比高估值龙头更平衡的交易选择。'}]},
 {symbol:'PLTR',name:'Palantir',sector:'AI 软件',cat:'earnings',logo:'PL',logoBg:'#4d5bd7',price:148.90,day:1.96,session:-0.11,week:5.30,month:21.70,ytd:67.50,rvol:2.2,avgVol:'49.8M',marketCap:'336.7B',high:-2.9,pe:186.0,sectorPe:41.5,fwdPe:122.4,ps:29.1,revGrowth:'+20.3%',epsGrowth:'+28.7%',btc:0.31,eth:0.25,nasdaq:0.70,beta:'1.61',event:'5天后财报',earningsMove:'+8.7%',btcSensitivity:'0.22×',summary:'股价距离 52 周高点仅 2.9%，但估值显著高于行业。财报前需要同时关注突破力度与估值消化能力。',valuationNote:'估值分位处于偏高区域，若基本面继续加速，市场可能继续容忍高估值；反之则面临快速压缩。',cryptoNote:'更多受 AI 软件叙事与成长股风险偏好影响，与加密相关性不高。',events:[{title:'下次财报 · 5天后',desc:'关注政府与商业客户增长，以及利润率能否继续改善。'}, {title:'距离前高仅 2.9%',desc:'财报结果可能直接决定是突破还是回落。'}, {title:'高估值窗口',desc:'高估值会放大市场对任何指引变化的反应。'}]},
 {symbol:'AMD',name:'AMD',sector:'半导体',cat:'ai',logo:'AM',logoBg:'#1e1e1e',price:181.35,day:3.15,session:0.28,week:4.44,month:7.80,ytd:21.60,rvol:2.0,avgVol:'63.7M',marketCap:'293.5B',high:-11.2,pe:41.8,sectorPe:26.3,fwdPe:32.9,ps:10.5,revGrowth:'+17.8%',epsGrowth:'+23.4%',btc:0.35,eth:0.27,nasdaq:0.81,beta:'1.76',event:'18天后财报',earningsMove:'+6.2%',btcSensitivity:'0.31×',summary:'受益于半导体板块整体走强，但与 NVDA 相比，30 日相对表现仍偏弱。',valuationNote:'估值略高于行业平均，但在 AI 受益股中仍处可接受区间，交易重点在于加速兑现。',cryptoNote:'主要仍是科技链标的，加密关联度明显弱于加密概念股。',events:[{title:'下次财报 · 18天后',desc:'关注数据中心产品推进与 AI 芯片出货节奏。'}, {title:'上次财报后 +6.2%',desc:'表明业绩窗口同样可能带来较大方向性波动。'}, {title:'相对弱势补涨',desc:'若板块扩散，AMD 常常承担第二梯队补涨角色。'}]},
 {symbol:'HOOD',name:'Robinhood',sector:'金融科技',cat:'crypto',logo:'HO',logoBg:'#15a05c',price:112.84,day:4.64,session:0.76,week:6.11,month:19.30,ytd:44.80,rvol:2.6,avgVol:'24.1M',marketCap:'97.2B',high:-6.8,pe:57.2,sectorPe:22.4,fwdPe:39.6,ps:13.7,revGrowth:'+26.4%',epsGrowth:'+31.8%',btc:0.58,eth:0.46,nasdaq:0.68,beta:'1.54',event:'14天后财报',earningsMove:'+7.9%',btcSensitivity:'0.63×',summary:'加密市场活跃度回升通常利好交易平台型公司，HOOD 同时受到股票与加密业务增长预期影响。',valuationNote:'估值高于传统券商，但平台型增长与产品扩张给予了一定溢价。需要交易活跃度持续验证。',cryptoNote:'对 BTC 的敏感度弱于 COIN/MSTR，但能更稳定地反映零售交易情绪回升。',events:[{title:'下次财报 · 14天后',desc:'关注零售交易活跃度、期权收入与加密业务增速。'}, {title:'上次财报后 +7.9%',desc:'通常反映用户增长与成交恢复对股价的正向反馈。'}, {title:'零售情绪指标',desc:'其走势经常能辅助判断散户风险偏好是否正在上升。'}]}
];

let watchlist=new Set(['NVDA','COIN']);
let activeFilter='all', sortKey=null, sortAsc=false;
